# Generated by Django 5.2.6 on 2025-10-28 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='next_trigger_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('once', 'Una vez'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('custom', 'Personalizado')], default='once', max_length=50),
        ),
        migrations.CreateModel(
            name='ReminderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='reminders.reminder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessible_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reminder', 'user')},
            },
        ),
    ]
