# Generated by Django 5.2.6 on 2025-10-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_options_reminder_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminderaccess',
            old_name='granted_at',
            new_name='added_at',
        ),
        migrations.AddField(
            model_name='reminderaccess',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminderaccess',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
