# Generated by Django 5.2.6 on 2025-10-16 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('family', 'Family'), ('doctor', 'Doctor')], default='family', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_others', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_to_others', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'shared_with')},
            },
        ),
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('granted', 'Acceso concedido'), ('revoked', 'Acceso revocado'), ('accepted', 'Acceso aceptado'), ('invited', 'Invitación enviada')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_history_owner', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_history_shared', to=settings.AUTH_USER_MODEL)),
                ('shared_access', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='shared_access.sharedaccess')),
            ],
        ),
        migrations.CreateModel(
            name='SharedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
