# Generated by Django 5.2.6 on 2025-10-19 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesshistory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_history_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='shared_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_history_shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedaccess',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedaccess',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_to_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='shared_access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='shared_access.sharedaccess'),
        ),
        migrations.AddField(
            model_name='sharedaccesstoken',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sharedaccess',
            unique_together={('owner', 'shared_with')},
        ),
    ]
