# Generated by Django 5.2.6 on 2025-10-19 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugvariant',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='medications.drug'),
        ),
        migrations.AddField(
            model_name='medication',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medication',
            name='drug_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.drugvariant'),
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unsafemedication',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsafe_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unsafemedication',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.drug'),
        ),
        migrations.AddField(
            model_name='unsafemedication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsafe_medications', to=settings.AUTH_USER_MODEL),
        ),
    ]
