# Generated by Django 5.2.6 on 2025-11-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='created_by_patient',
            field=models.BooleanField(default=False),
        ),
    ]
